### ISSUE TITLE
Failed to jump properly

### ISSUE THREAD

**Issue by TrustTheBoy** [brentvatne/react-navigation-addon-search-layout#1]
In Search Modal, using `this.props.navigation.navigate("HomeTwo")` to jump to the specified page will automatically return to `Main`, you can add multiple screens in Main in your case and try to jump

as:

```JavaScript
const MainStack = StackNavigator(
  {
    Home: {
      screen: Home
    },
HomeTwo: {
      screen: HomeTwo
    },
  },
  ...
);

const Navigation = StackNavigator(
  {
    Main: {
      screen: MainStack,
    },
    Search: {
      screen: SearchLayout
    },
  },
 ... 
}
```

**Comment by brentvatne** [comment]
i added an example to the README.md that might be useful. sorry i haven't looked at this repo in a while :(
